"""init

Revision ID: b8fa3f44e585
Revises: 
Create Date: 2020-01-29 08:20:12.925319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fa3f44e585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postURL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=5000), nullable=True),
    sa.Column('website_name', sa.String(length=5000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postURL_timestamp'), 'postURL', ['timestamp'], unique=False)
    op.create_table('scrapped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('browser', sa.String(length=5000), nullable=True),
    sa.Column('time', sa.String(length=5000), nullable=True),
    sa.Column('unique_time', sa.String(length=5000), nullable=True),
    sa.Column('ip_request', sa.String(length=5000), nullable=True),
    sa.Column('country', sa.String(length=5000), nullable=True),
    sa.Column('region', sa.String(length=5000), nullable=True),
    sa.Column('zipcode', sa.String(length=5000), nullable=True),
    sa.Column('city', sa.String(length=5000), nullable=True),
    sa.Column('latitude', sa.String(length=5000), nullable=True),
    sa.Column('longitude', sa.String(length=5000), nullable=True),
    sa.Column('website_name', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selected_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=5000), nullable=True),
    sa.Column('website_name', sa.String(length=5000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_data_timestamp'), 'selected_data', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_selected_data_timestamp'), table_name='selected_data')
    op.drop_table('selected_data')
    op.drop_table('scrapped_data')
    op.drop_index(op.f('ix_postURL_timestamp'), table_name='postURL')
    op.drop_table('postURL')
    # ### end Alembic commands ###
